version: '2'

services:

  account-cp-zookeeper-headless:
    image: confluent/zookeeper
    ports:
      - "2181:2181"

  account-cp-kafka-headless:
    image: confluent/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "192.168.99.100"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: "account-cp-zookeeper-headless:2181"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - account-cp-zookeeper-headless

  account-server:
    image: accountserver:latest
    ports:
      - "8080:8080"
    depends_on:
    - account-cp-kafka-headless

  account-tx-log:
    image: accounttxlog:latest
    ports:
      - "8081:8081"
    depends_on:
      - account-cp-kafka-headless
      - account-server

  account-traffic:
    image: accounttraffic:latest
    ports:
      - "8082:8082"
    depends_on:
      - account-server
      - account-tx-log
