apiVersion: v1
kind: Pod
metadata:
  name: account-traffic
  labels:
    app: account-traffic
spec:
  containers:
    - name: account-traffic-container
      image: accounttraffic:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080